### PR TITLE
actual nsfw impl

### PR DESCRIPTION
**Pull request by AnhNguyenlost13**
why??

### CODE REVIEW

**Comment by a-catgirl-dev** [comment]
great way to start off my morning, anh.

**Comment by a-catgirl-dev** [comment]
@AnhNguyenlost13, by chance, did you end up *testing* this?

**Comment by AnhNguyenlost13** [comment]
no no no it's untested i swear

**Comment by WilliamAnimate** [comment]
> no no no it's untested i swear

**Comment by WilliamAnimate** [comment]
image fail; I'm officially moving to gitlab forever

**Comment by AnhNguyenlost13** [comment]
please please please tell me what you're trying to send

**Comment by a-catgirl-dev** [comment]
> no no no it's untested i swear

**Comment by AnhNguyenlost13** [comment]
i will give you Uranium-238 as cat food

**Comment by a-catgirl-dev** [comment]
> i will give you Uranium-238 as cat food

anh you didn't have to tell everyone that I was a catgirl :sob:

**Comment by a-catgirl-dev** [comment]
> > i will give you Uranium-238 as cat food
> 
> anh you didn't have to tell everyone that I was a catgirl :sob:

wait shit how do I delete in github

**Comment by AnhNguyenlost13** [comment]
> > i will give you Uranium-238 as cat food
> 
> anh you didn't have to tell everyone that I was a catgirl :sob:

you didn't have to tell everyone that i tested the code 😭

**Comment by a-catgirl-dev** [comment]
> > > i will give you Uranium-238 as cat food
> > 
> > 
> > anh you didn't have to tell everyone that I was a catgirl 😭
> 
> you didn't have to tell everyone that i tested the code 😭

**Comment by AnhNguyenlost13** [comment]
everything would've went for the good if you didn't doubt me

**Pull request merged**
