### PR TITLE
nekos.best support

### PR DESCRIPTION
**Pull request by a-catgirl-dev**
refactor the hell out of this project

### CODE REVIEW

**Comment by a-catgirl-dev** [comment]
I have a mental illness

**Comment by a-catgirl-dev** [comment]
I mean the tests pass so yolo

**Comment by Thusuzzee** [comment]
:3

**Comment by a-catgirl-dev** [comment]
> :3

:3

**Comment by a-catgirl-dev** [comment]
wait can I get your autograph

**Comment by Thusuzzee** [comment]
Yes sure
signature(1)

**Comment by a-catgirl-dev** [comment]
yayyyy

**Comment by Thusuzzee** [comment]
Well there was a [rust package](https://crates.io/crates/nekosbest), but that works perfectly fine as well, perhaps even better.
And you should totally join our [server](https://discord.com/invite/AsYnNuGcMj). Not self-adverting :clueless:

**Comment by a-catgirl-dev** [comment]
> Well there was a [rust package](https://crates.io/crates/nekosbest), but that works perfectly fine as well, perhaps even better.
> And you should totally join our [server](https://discord.com/invite/AsYnNuGcMj). Not self-adverting :clueless:

haha, I found out literally 10 minutes ago about the nekosbest crate (and now I'm gonna cry)

but then again I switched from reqwest to ureq sooooo probably not a good idea

**Pull request merged**
